function PortExtractorGUI()
% PortExtractorGUI  Simulink端口提取工具 — 图形界面版本
%
%   调用方式:  PortExtractorGUI
%
%   依赖:
%       PortExtractor.m  — 核心提取函数
%       Simulink 环境

    %% ========== 创建图形窗口 ==========
    hFig = figure( ...
        'Name',           'PortExtractor — Simulink 端口提取工具', ...
        'NumberTitle',    'off', ...
        'Position',       [500, 260, 480, 400], ...
        'MenuBar',        'none', ...
        'ToolBar',        'none', ...
        'Resize',         'off', ...
        'HandleVisibility', 'callback', ...
        'Color',          [0.94, 0.94, 0.94]);

    movegui(hFig, 'center');

    %% ========== 布局参数 ==========
    margin = 20;
    rowH   = 28;
    gap    = 10;
    labelW = 100;

    %% ========== 标题 ==========
    titleY = 310;
    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, titleY, 440, 30], ...
        'String', 'PortExtractor — Simulink 端口提取工具', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    %% ========== 模型名称行 ==========
    rowY = titleY - 50;
    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, rowY, labelW, rowH], ...
        'String', '模型名称:', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'right', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hModelEdit = uicontrol('Parent', hFig, ...
        'Style', 'edit', ...
        'Position', [margin + labelW + 5, rowY, 250, rowH], ...
        'String', '', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'white', ...
        'TooltipString', '输入模型名称（不含 .slx 后缀）');

    uicontrol('Parent', hFig, ...
        'Style', 'pushbutton', ...
        'Position', [margin + labelW + 5 + 255, rowY, 60, rowH], ...
        'String', '浏览', ...
        'FontSize', 10, ...
        'Callback', @onBrowse);

    %% ========== 起始子系统行 ==========
    rowY = rowY - (rowH + gap);
    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, rowY, labelW, rowH], ...
        'String', '起始子系统:', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'right', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hSubEdit = uicontrol('Parent', hFig, ...
        'Style', 'edit', ...
        'Position', [margin + labelW + 5, rowY, 195, rowH], ...
        'String', '', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'white', ...
        'TooltipString', '留空=根模型, 或输入如 ActDischarge_2ms/ActDischargeCalc');

    uicontrol('Parent', hFig, ...
        'Style', 'pushbutton', ...
        'Position', [margin + labelW + 5 + 200, rowY, 80, rowH], ...
        'String', '选择子系统', ...
        'FontSize', 9, ...
        'Callback', @onSelectSub);

    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin + labelW + 5 + 285, rowY, 80, rowH], ...
        'String', '(留空=根模型)', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    %% ========== 搜索深度 + 复选框 ==========
    rowY = rowY - (rowH + gap);
    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, rowY, labelW, rowH], ...
        'String', '搜索深度:', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'right', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hSearchDepth = uicontrol('Parent', hFig, ...
        'Style', 'edit', ...
        'Position', [margin + labelW + 5, rowY, 60, rowH], ...
        'String', '1', ...
        'FontSize', 10, ...
        'BackgroundColor', 'white', ...
        'TooltipString', '1=仅当前层, 2=当前+下一层...');

    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin + labelW + 5 + 65, rowY, 120, rowH], ...
        'String', '(1=仅当前层)', ...
        'FontSize', 9, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hIncludeTE = uicontrol('Parent', hFig, ...
        'Style', 'checkbox', ...
        'Position', [margin + labelW + 5 + 65 + 125, rowY, 155, rowH], ...
        'String', '包含触发/使能', ...
        'FontSize', 10, ...
        'BackgroundColor', [0.94, 0.94, 0.94], ...
        'Value', 0);

    %% ========== 文件名时间戳 ==========
    rowY = rowY - (rowH + gap);
    hTimestamp = uicontrol('Parent', hFig, ...
        'Style', 'checkbox', ...
        'Position', [margin + labelW + 5, rowY, 250, rowH], ...
        'String', '文件名添加时间戳', ...
        'FontSize', 10, ...
        'BackgroundColor', [0.94, 0.94, 0.94], ...
        'Value', 0);

    %% ========== 提取按钮 ==========
    btnY = rowY - (rowH + gap + 10);
    hExtractBtn = uicontrol('Parent', hFig, ...
        'Style', 'pushbutton', ...
        'Position', [margin, btnY, 440, 40], ...
        'String', '提  取  端  口', ...
        'FontSize', 13, ...
        'FontWeight', 'bold', ...
        'ForegroundColor', [1, 1, 1], ...
        'BackgroundColor', [0.30, 0.55, 0.95], ...
        'Callback', @onExtract);

    %% ========== 状态栏 ==========
    statusY = btnY - (rowH + gap);
    hStatus = uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, statusY, 440, rowH], ...
        'String', '状态: 等待操作...', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94], ...
        'ForegroundColor', [0.3, 0.3, 0.3]);

    %% ========== 结果摘要 ==========
    resultY = statusY - (rowH + 5);
    uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin, resultY + 5, 440, 18], ...
        'String', '─ 结果摘要 ─', ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hResultIn = uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin + 20, resultY - 22, 200, 18], ...
        'String', '输入端口: -- 个', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hResultOut = uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin + 230, resultY - 22, 200, 18], ...
        'String', '输出端口: -- 个', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    hResultFile = uicontrol('Parent', hFig, ...
        'Style', 'text', ...
        'Position', [margin + 20, resultY - 44, 420, 18], ...
        'String', '输出文件: --', ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);

    %% ========== 回调函数 ==========

    % ---------- 浏览 ----------
    function onBrowse(~, ~)
        [file, path] = uigetfile( ...
            {'*.slx', 'Simulink 模型文件 (*.slx)'; '*.*', '所有文件 (*.*)'}, ...
            '选择 Simulink 模型');
        if isequal(file, 0)
            return
        end
        [~, name] = fileparts(file);
        hModelEdit.String = name;
        if ~bdIsLoaded(name)
            try
                load_system(fullfile(path, file));
                setStatus(sprintf('已加载: %s', name), [0, 0.5, 0]);
            catch ME
                setStatus(sprintf('加载失败: %s', ME.message), [0.8, 0, 0]);
                warndlg(sprintf('无法加载 "%s":\n%s', name, ME.message), '加载失败', 'modal');
            end
        else
            setStatus(sprintf('已加载: %s', name), [0, 0.5, 0]);
        end
    end

    % ---------- 选择子系统 ----------
    function onSelectSub(~, ~)
        modelStr = strtrim(hModelEdit.String);
        if isempty(modelStr)
            setStatus('请先输入模型名称', [0.8, 0, 0]);
            return
        end
        if ~bdIsLoaded(modelStr)
            setStatus('模型未加载', [0.8, 0, 0]);
            return
        end

        % 只找真实的子系统（排除 Compare To Constant 等 masked 块）
        allSubs = find_system(modelStr, ...
            'BlockType', 'SubSystem', ...
            'Mask',      'off');

        if isempty(allSubs)
            setStatus('未找到真实子系统', [0.8, 0.5, 0]);
            warndlg('模型中未找到任何非掩码的子系统。', '提示', 'modal');
            return
        end

        % 构建列表（显示相对路径）
        listStr = {};
        for i = 1:numel(allSubs)
            fullP = allSubs{i};
            relP = fullP(numel(modelStr)+2:end);
            listStr{end+1} = relP;
        end

        % 选择
        selIdx = selectFromList(listStr, ...
            '选择起始子系统', ...
            '选择一个子系统（仅显示真实子系统，已排除 Compare To Constant 等掩码块）：');

        if ~isempty(selIdx) && selIdx > 0 && selIdx <= numel(listStr)
            hSubEdit.String = listStr{selIdx};
            setStatus(sprintf('已选: %s', listStr{selIdx}), [0, 0.5, 0]);
        end
    end

    % ---------- 提取 ----------
    function onExtract(~, ~)
        modelStr    = strtrim(hModelEdit.String);
        subStr      = strtrim(hSubEdit.String);
        searchStr   = strtrim(hSearchDepth.String);

        if isempty(modelStr)
            setStatus('请输入模型名称', [0.8, 0, 0]);
            errordlg('请输入模型名称。', '参数错误', 'modal');
            return
        end

        searchDepth = str2double(searchStr);
        if isnan(searchDepth) || searchDepth < 1 || round(searchDepth) ~= searchDepth
            setStatus('搜索深度必须是正整数', [0.8, 0, 0]);
            errordlg('搜索深度必须是正整数（1, 2, 3, ...）。', '参数错误', 'modal');
            return
        end

        % 加载模型
        if ~bdIsLoaded(modelStr)
            try
                load_system(modelStr);
                setStatus(sprintf('已加载: %s', modelStr), [0, 0.5, 0]);
            catch ME
                setStatus(sprintf('无法加载: %s', ME.message), [0.8, 0, 0]);
                errordlg(sprintf('无法加载模型 "%s":\n%s', modelStr, ME.message), '加载失败', 'modal');
                return
            end
        end

        % 提取
        hExtractBtn.Enable = 'off';
        hExtractBtn.String = '正在提取...';
        if isempty(subStr)
            setStatus(sprintf('正在提取 (根模型)... 搜索=%d层', searchDepth), [0.3, 0.3, 0.8]);
        else
            setStatus(sprintf('正在提取 (%s)... 搜索=%d层', subStr, searchDepth), [0.3, 0.3, 0.8]);
        end
        drawnow;

        try
            includeTE = logical(get(hIncludeTE, 'Value'));
            useTS     = logical(get(hTimestamp, 'Value'));
            filepath  = PortExtractor(modelStr, searchDepth, includeTE, subStr, useTS);

            actualIn  = 0; actualOut = 0;
            try
                [~,~,rI] = xlsread(filepath, 'Inputs');
                [~,~,rO] = xlsread(filepath, 'Outputs');
                actualIn  = max(0, size(rI,1)-1);
                actualOut = max(0, size(rO,1)-1);
            catch
            end

            hResultIn.String   = sprintf('输入端口: %d 个', actualIn);
            hResultOut.String  = sprintf('输出端口: %d 个', actualOut);
            hResultFile.String = sprintf('输出文件: %s', filepath);

            setStatus(sprintf('完成！输入:%d  输出:%d', actualIn, actualOut), [0, 0.5, 0]);
            msgbox(sprintf('输入:%d  输出:%d\n\n%s', actualIn, actualOut, filepath), '完成', 'help');

        catch ME
            setStatus(sprintf('失败: %s', ME.message), [0.8, 0, 0]);
            errordlg(sprintf('提取失败:\n%s', ME.message), '错误', 'modal');
        end

        hExtractBtn.Enable = 'on';
        hExtractBtn.String = '提  取  端  口';
    end

    %% ---------- 状态更新 ----------
    function setStatus(msg, color)
        hStatus.String = ['状态: ', msg];
        if nargin >= 2
            hStatus.ForegroundColor = color;
        end
        drawnow;
    end

end

%% ---------- 自建列表选择对话框 ----------
function selIdx = selectFromList(listStr, dlgTitle, promptStr)
    d = dialog('Name', dlgTitle, ...
        'Position', [500, 280, 520, 420], ...
        'WindowStyle', 'modal');

    uicontrol('Parent', d, 'Style', 'text', ...
        'Position', [20, 380, 480, 25], ...
        'String', promptStr, ...
        'HorizontalAlignment', 'left', ...
        'FontSize', 10);

    hList = uicontrol('Parent', d, 'Style', 'listbox', ...
        'Position', [20, 50, 480, 320], ...
        'String', listStr, ...
        'FontSize', 10, ...
        'Value', 1, ...
        'Max', 1, 'Min', 0);

    selIdx = [];

    uicontrol('Parent', d, 'Style', 'pushbutton', ...
        'Position', [180, 10, 70, 28], ...
        'String', '确定', ...
        'FontSize', 10, ...
        'Callback', @(~,~) onOK());

    uicontrol('Parent', d, 'Style', 'pushbutton', ...
        'Position', [270, 10, 70, 28], ...
        'String', '取消', ...
        'FontSize', 10, ...
        'Callback', @(~,~) delete(d));

    function onOK()
        selIdx = get(hList, 'Value');
        delete(d);
    end

    uiwait(d);
end
